const colors = {
  light: {
    text: "#1C2B1C",
    tint: "#2C5F2E",
    background: "#F5F2EB",
    foreground: "#1C2B1C",
    card: "#FFFFFF",
    cardForeground: "#1C2B1C",
    primary: "#2C5F2E",
    primaryForeground: "#FFFFFF",
    secondary: "#EBF0E8",
    secondaryForeground: "#2C5F2E",
    muted: "#F0EDE5",
    mutedForeground: "#8A9080",
    accent: "#6B9E45",
    accentForeground: "#FFFFFF",
    destructive: "#C0392B",
    destructiveForeground: "#FFFFFF",
    border: "#DDD8CC",
    input: "#E5E0D8",
  },
  dark: {
    text: "#E8F0E8",
    tint: "#97BC62",
    background: "#111811",
    foreground: "#E8F0E8",
    card: "#1E2A1E",
    cardForeground: "#E8F0E8",
    primary: "#97BC62",
    primaryForeground: "#1C2B1C",
    secondary: "#253325",
    secondaryForeground: "#A8CC88",
    muted: "#1E2A1E",
    mutedForeground: "#7A9070",
    accent: "#97BC62",
    accentForeground: "#1C2B1C",
    destructive: "#E74C3C",
    destructiveForeground: "#FFFFFF",
    border: "#2E3E2E",
    input: "#2E3E2E",
  },
  radius: 14,
};

export default colors;
